# Generated by Django 3.2.8 on 2021-10-08 08:31

from django.db import migrations, models
import myapi.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(validators=[myapi.validators.validate_time_15]),
        ),
    ]
